import {Client,Interaction,SlashCommandBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,AttachmentBuilder} from "discord.js";
import fs from "node:fs/promises"; import path from "node:path"; import crypto from "node:crypto";
import {ensureUser,effectiveRole,ROLE_LABEL,hasRoleAtLeast,getUser,getUserByDiscordId,setBan,setPlan} from "./roles.js";
import {db,nowMs} from "./db.js"; import {getBalance,addCredits,setCredits,takeCredits,deductCredit,refundCredit,InsufficientCreditsError} from "./credits.js";
import {IPHONE_MODELS,findModel} from "./models.js"; import {IMAGE_COST,MAX_IMAGE_BYTES,TMP_DIR,SUPPORT_CONTACT} from "./config.js";
import {resizeToAppleSensor,analyzeBrightness,pickRealisticExposure,encodeAsHeic} from "./image.js"; import {injectIPhoneExif} from "./exif.js";
import {submit,QueueFullError,UserBusyError,DuplicateJobError} from "./queue.js"; import {writeLog,recentLogs,clearLogs} from "./logs.js";
import {analyticsSummary,serverStats,topModelsTable,topUsersTable} from "./analytics.js"; import {logger} from "./logger.js";

const C=(new SlashCommandBuilder()).setName("start").setDescription("Show the bot panel.");
export const commandDefinitions=[C,new SlashCommandBuilder().setName("help").setDescription("Show help."),new SlashCommandBuilder().setName("credits").setDescription("Check credits."),new SlashCommandBuilder().setName("models").setDescription("List iPhone models."),new SlashCommandBuilder().setName("plan").setDescription("Show your plan."),new SlashCommandBuilder().setName("stats").setDescription("Show your stats."),new SlashCommandBuilder().setName("history").setDescription("Show image history."),new SlashCommandBuilder().setName("feedback").setDescription("Send feedback.").addStringOption(o=>o.setName("message").setDescription("Feedback").setRequired(true)),new SlashCommandBuilder().setName("image").setDescription("Process an image with iPhone EXIF.").addAttachmentOption(o=>o.setName("image").setDescription("Image").setRequired(true)),new SlashCommandBuilder().setName("userinfo").setDescription("Look up a user.").addUserOption(o=>o.setName("user").setDescription("User").setRequired(true)),new SlashCommandBuilder().setName("ban").setDescription("Ban a bot user.").addUserOption(o=>o.setName("user").setDescription("User").setRequired(true)),new SlashCommandBuilder().setName("unban").setDescription("Unban a bot user.").addUserOption(o=>o.setName("user").setDescription("User").setRequired(true)),new SlashCommandBuilder().setName("setcredits").setDescription("Set credits.").addUserOption(o=>o.setName("user").setDescription("User").setRequired(true)).addIntegerOption(o=>o.setName("amount").setDescription("Amount").setRequired(true)),new SlashCommandBuilder().setName("addcredits").setDescription("Add credits.").addUserOption(o=>o.setName("user").setDescription("User").setRequired(true)).addIntegerOption(o=>o.setName("amount").setDescription("Amount").setRequired(true)),new SlashCommandBuilder().setName("takecredits").setDescription("Take credits.").addUserOption(o=>o.setName("user").setDescription("User").setRequired(true)).addIntegerOption(o=>o.setName("amount").setDescription("Amount").setRequired(true)),new SlashCommandBuilder().setName("setplan").setDescription("Set plan.").addUserOption(o=>o.setName("user").setDescription("User").setRequired(true)).addStringOption(o=>o.setName("plan").setDescription("Plan").setRequired(true).addChoices({name:"Free",value:"free"},{name:"Pro",value:"pro"},{name:"VIP",value:"vip"})),new SlashCommandBuilder().setName("analytics").setDescription("Analytics."),new SlashCommandBuilder().setName("serverstats").setDescription("Server stats."),new SlashCommandBuilder().setName("topusers").setDescription("Top users."),new SlashCommandBuilder().setName("topmodels").setDescription("Top models."),new SlashCommandBuilder().setName("logs").setDescription("Recent logs."),new SlashCommandBuilder().setName("clearlogs").setDescription("Clear logs.")].map(x=>x.toJSON());

type Pending={url:string;name:string}; const pending=new Map<string,Pending>();
const roleGate=(i:Interaction,r:any)=>hasRoleAtLeast(ensureUser(i.user.id,i.user.username,i.user.globalName??i.user.username),r);
const rows=()=>{const b=IPHONE_MODELS.map(m=>new ButtonBuilder().setCustomId("model:"+m.key).setLabel(m.label).setStyle(ButtonStyle.Secondary));const out:any[]=[];for(let n=0;n<b.length;n+=2)out.push(new ActionRowBuilder<ButtonBuilder>().addComponents(b.slice(n,n+2)));return out};

export function registerDiscordHandlers(client:Client){
 client.on("interactionCreate",async i=>{if(!i.isRepliable())return;ensureUser(i.user.id,i.user.username,i.user.globalName??i.user.username);try{if(i.isChatInputCommand())await command(i);else if(i.isButton())await button(i)}catch(e){logger.error({err:e},"interaction failed");if(i.replied||i.deferred)await i.editReply("Something went wrong.").catch(()=>{});else await i.reply({content:"Something went wrong.",ephemeral:true}).catch(()=>{})}});
}
async function command(i:any){
 const id=ensureUser(i.user.id,i.user.username,i.user.globalName??i.user.username).user_id,u=getUser(id)!;
 if(effectiveRole(u)==="banned")return i.reply({content:"You are banned.",ephemeral:true});
 switch(i.commandName){
 case"start":case"help":return i.reply({embeds:[new EmbedBuilder().setTitle("📸 iMetaLens").setDescription("Realistic iPhone EXIF metadata, on demand.").addFields({name:"Rank",value:ROLE_LABEL[effectiveRole(u)],inline:true},{name:"Credits",value:String(u.credits),inline:true},{name:"Cost",value:IMAGE_COST+"/image",inline:true},{name:"Commands",value:"/image /credits /models /plan /stats /history /feedback"})]});
 case"credits":return i.reply(`You have **${getBalance(id)}** credits.`);
 case"models":return i.reply(IPHONE_MODELS.map(m=>`• **${m.label}** — ${m.megapixels} MP`).join("\n"));
 case"plan":return i.reply(`Plan: **${u.plan}**\nFree · Pro · VIP\nSupport: ${SUPPORT_CONTACT}`);
 case"stats":{const n=(db.prepare("SELECT COUNT(*) n FROM images WHERE user_id=?").get(id) as any).n;return i.reply(`Role: **${ROLE_LABEL[effectiveRole(u)]}**\nPlan: **${u.plan}**\nCredits: **${u.credits}**\nImages: **${n}**`)}
 case"history":{const a=db.prepare("SELECT model,created_at FROM images WHERE user_id=? ORDER BY id DESC LIMIT 10").all(id) as any[];return i.reply(a.length?a.map((x,n)=>`${n+1}. ${x.model} — <t:${Math.floor(x.created_at/1000)}:f>`).join("\n"):"No history yet.")}
 case"feedback":{const m=i.options.getString("message",true);db.prepare("INSERT INTO feedback(user_id,message,timestamp) VALUES(?,?,?)").run(id,m,nowMs());return i.reply({content:"Feedback received.",ephemeral:true})}
 case"image":return image(i);
 case"userinfo":if(!roleGate(i,"moderator"))return i.reply({content:"No permission.",ephemeral:true});{const x=getUserByDiscordId(i.options.getUser("user",true).id);return i.reply(x?`<@${x.user_id}> · ${ROLE_LABEL[effectiveRole(x)]} · ${x.plan} · ${x.credits} credits`:"User not found.")}
 case"ban":case"unban":if(!roleGate(i,"moderator"))return i.reply({content:"No permission.",ephemeral:true});return i.reply(setBan(getUserByDiscordId(i.options.getUser("user",true).id)?.user_id??-1,i.commandName==="ban")?"Updated.":"Cannot update.");
 case"setcredits":case"addcredits":case"takecredits":if(!roleGate(i,"admin"))return i.reply({content:"No permission.",ephemeral:true});{const target=getUserByDiscordId(i.options.getUser("user",true).id); if(!target)return i.reply({content:"User has not used the bot yet.",ephemeral:true}); const x=target.user_id,a=i.options.getInteger("amount",true);if(i.commandName==="setcredits")setCredits(x,a);else if(i.commandName==="addcredits")addCredits(x,a);else takeCredits(x,a);return i.reply("Credits updated.");}
 case"setplan":if(!roleGate(i,"admin"))return i.reply({content:"No permission.",ephemeral:true});setPlan(getUserByDiscordId(i.options.getUser("user",true).id)?.user_id??-1,i.options.getString("plan",true) as any);return i.reply("Plan updated.");
 case"analytics":if(!roleGate(i,"admin"))return i.reply({content:"No permission.",ephemeral:true});return i.reply(analyticsSummary());
 case"serverstats":if(!roleGate(i,"admin"))return i.reply({content:"No permission.",ephemeral:true});return i.reply(serverStats());
 case"topusers":if(!roleGate(i,"admin"))return i.reply({content:"No permission.",ephemeral:true});return i.reply(topUsersTable());
 case"topmodels":if(!roleGate(i,"moderator"))return i.reply({content:"No permission.",ephemeral:true});return i.reply(topModelsTable());
 case"logs":if(!roleGate(i,"moderator"))return i.reply({content:"No permission.",ephemeral:true});return i.reply((recentLogs(20) as any[]).map(x=>`[${new Date(x.timestamp).toISOString().slice(11,19)}] ${x.type} ${x.action}`).join("\n")||"No logs.");
 case"clearlogs":if(!roleGate(i,"admin"))return i.reply({content:"No permission.",ephemeral:true});return i.reply(`Cleared ${clearLogs()} logs.`);
 }
}
async function image(i:any){const a=i.options.getAttachment("image",true);if(!a.contentType?.startsWith("image/"))return i.reply({content:"Upload an image.",ephemeral:true});if(a.size>MAX_IMAGE_BYTES)return i.reply({content:"Maximum image size is 20 MB.",ephemeral:true});pending.set(i.user.id,{url:a.url,name:a.name||"image"});return i.reply({content:"Choose the iPhone model:",components:rows(),ephemeral:true})}
async function button(i:any){const [p,k]=i.customId.split(":");if(p!=="model")return;const x=pending.get(i.user.id),m=findModel(k);if(!x||!m)return i.reply({content:"Selection expired. Run /image again.",ephemeral:true});pending.delete(i.user.id);await i.deferReply({ephemeral:true});const id=ensureUser(i.user.id,i.user.username,i.user.globalName??i.user.username).user_id;let charged=false;try{deductCredit(id,IMAGE_COST,"image_exif");charged=true;const key=`img:${id}:${crypto.createHash("sha256").update(x.url).digest("hex")}:${m.key}`;await submit({userId:id,jobKey:key},async jc=>{const dir=path.join(TMP_DIR,"discord_"+crypto.randomBytes(5).toString("hex"));await fs.mkdir(dir,{recursive:true});try{await i.editReply("⏳ Processing…");const r=await fetch(x.url,{signal:jc.signal});if(!r.ok)throw Error("download failed");const buf=Buffer.from(await r.arrayBuffer());const input=path.join(dir,"input");await fs.writeFile(input,buf);const resized=await resizeToAppleSensor(input,m.megapixels);const ex=pickRealisticExposure(await analyzeBrightness(resized.outputPath));const heic=await encodeAsHeic(resized.outputPath);const out=await injectIPhoneExif(heic.outputPath,m,{width:resized.width,height:resized.height},new Date(),ex);await i.editReply({content:`✅ ${m.label} EXIF applied.`,files:[new AttachmentBuilder(out.outputPath,{name:"IMG_iPhone.heic"})]});db.prepare("INSERT INTO images(user_id,model,message_id,file_unique,created_at) VALUES(?,?,?,?,?)").run(id,m.label,0,key,nowMs());writeLog({type:"image",userId:id,action:"exif_injected",meta:{model:m.label,iso:ex.iso}});await out.cleanup()}finally{await fs.rm(dir,{recursive:true,force:true}).catch(()=>{})}});charged=false}catch(e){if(charged)refundCredit(id,IMAGE_COST,"pipeline_failure");const msg=e instanceof InsufficientCreditsError?`Not enough credits. You have ${e.available}.`:e instanceof QueueFullError?"Queue is full.":e instanceof UserBusyError?"You already have an image processing.":e instanceof DuplicateJobError?"That image is already processing.":"Processing failed; your credit was refunded.";await i.editReply(msg).catch(()=>{})}}
